puppy = (
    "Puppy",
    ('Bella Poodle', 'Charlie Labrador', 'Max Dachshund', 'Lucy Golden Retriever', 'Cooper Beagle', 'Lola French Bulldog', 'Bailey Shih Tzu', 'Rocky Boxer', 'Sadie German Shepherd', 'v', 'Molly Yorkshire Terrier', 'Duke Bulldog', 'Zoe Chihuahua', 'Oliver Shiba Inu', 'Lily Maltese', 'Tucker Pomeranian', 'Ruby Doberman', 'Winston Rottweiler', 'Coco Husky', 'Rosie Great Dane', 'Zeus Australian Shepherd', 'Luna Shetland Sheepdog', 'Riley Border Collie', 'Chloe Shiba Inu', 'Bear Saint Bernard', 'Penny Cocker Spaniel', 'Leo Pug', 'Sasha Boxer', 'Milo Shih Tzu', 'Daisy Shetland Sheepdog', 'Jack Jack Russell Terrier', 'Sophie Poodle', 'Oscar Dachshund', 'Lilly Shetland Sheepdog', 'Bentley Shih Tzu', 'Zoey Beagle', 'Cody Bulldog', 'Abby German Shepherd', 'Jax Labrador', 'Koda Siberian Husky', 'Emma Pomeranian', 'Sam Corgi', 'Gus Shih Tzu', 'Lulu Poodle', 'Jasper Shiba Inu', 'Maddie French Bulldog', 'Hank Boxer', 'Roxy Cocker Spaniel', 'Zeke Beagle', 'Gracie Dachshund', 'Finn Australian Shepherd', 'Stella Shetland Sheepdog', 'Louie Pug', 'Cleo Maltese', 'Simba Persian Cat', 'Nala Siamese Cat', 'Rusty Bengal Cat', 'Mia Ragdoll Cat', 'Toby Maine Coon Cat', 'Lady Cat', 'Winnie Persian Cat', 'Kobe Siamese Cat', 'Lexi Bengal Cat', 'Charlie Ragdoll Cat', 'Gigi Maine Coon Cat', 'Mocha Abyssinian Cat', 'Minnie Sphynx Cat', 'Dexter Ragdoll Cat', 'Piper Siamese Cat', 'Bruno Bengal Cat', 'Callie Ragdoll Cat', 'Otis Maine Coon Cat', 'Poppy Sphynx Cat', 'Ace Siamese Cat', 'Athena Bengal Cat', 'Kai Ragdoll Cat', 'Remy Maine Coon Cat', 'Willow Sphynx Cat', 'Rocco Siamese Cat', 'Harley Bengal Cat', 'Maggie Ragdoll Cat', 'Hudson Maine Coon Cat', 'Griffin Sphynx Cat', 'Cupcake Siamese Cat', 'Olivia Bengal Cat', 'Gizmo Ragdoll Cat', 'Ziggy Maine Coon Cat', 'Ella Sphynx Cat', 'Tank Siamese Cat', 'Ruby Bengal Cat', 'Pippin Ragdoll Cat', 'Chester Maine Coon Cat', 'Aurora Sphynx Cat', 'Loki Siamese Cat', 'Zara Bengal Cat', 'Sunny Ragdoll Cat', 'Mia Maine Coon Cat', 'Mango Sphynx Cat', 'Pepper Siamese Cat', 'Trixie Bengal Cat', 'Joey Ragdoll Cat', 'Layla Maine Coon Cat', 'Blue Sphynx Cat', 'Harper Siamese Cat', 'Daisy Bengal Cat', 'Apollo Ragdoll Cat', 'Nova Maine Coon Cat', 'Rusty Sphynx Cat', 'Ginger Siamese Cat', 'Pablo Bengal Cat')
)

cosmic = (
    "Cosmic",
    ("Mercury Planet", "Venus Planet", "Earth Planet", "Mars Planet", "Jupiter Planet", "Saturn Planet", "Uranus Planet", "Neptune Planet", "Pluto Planet", "Alpha Centauri A Star", "Alpha Centauri B Star", "Betelgeuse Star", "Rigel Star", "Vega Star", "Arcturus Star", "Aldebaran Star", "Antares Star", "Procyon Star", "Deneb Star", "Mars Moon Phobos", "Mars Moon Deimos", "Ganymede Moon", "Callisto Moon", "Io Moon", "Europa Moon", "Titan Moon", "Triangulum Galaxy", "Sombrero Galaxy", "Whirlpool Galaxy", "Pinwheel Galaxy", "Messier 87 Galaxy", "Antennae Galaxies", "Large Magellanic Cloud Galaxy", "Small Magellanic Cloud Galaxy", "Sculptor Galaxy", "Andromeda Galaxy", "Vesta Asteroid", "Pallas Asteroid", "Hygiea Asteroid", "Eunomia Asteroid", "Psyche Asteroid", "Juno Asteroid", "Ceres Dwarf Planet", "Chiron Asteroid", "Icarus Asteroid", "Davida Asteroid", "Alpha Proxima Star", "Sirius Star", "Betelgeuse Star", "Polaris Star", "R136a1 Star", "Eta Carinae Star", "WR 104 Star", "Algol Star", "R Doradus Star", "RX J0806.4-4123 Star", "Cygnus X-1 Star", "Orion Nebula", "Eagle Nebula", "Cat's Eye Nebula", "Crab Nebula", "Boomerang Nebula", "Helix Nebula", "Horsehead Nebula", "Omega Centauri Star Cluster", "Messier 13 Star Cluster", "Pleiades Star Cluster", "Hyades Star Cluster", "Comet Hale-Bopp", "Comet Halley", "Asteroid Eros", "Asteroid Itokawa", "Asteroid Bennu", "Asteroid Apophis", "Taurus Molecular Cloud", "Eskimo Nebula", "NGC 6302 Butterfly Nebula", "Messier 78 Nebula", "Messier 1 - The Crab Nebula", "NGC 7293 - The Helix Nebula", "Messier 17 - Omega Nebula", "IC 434 - Horsehead Nebula", "NGC 6826 - Blinking Nebula", "IC 2118 - Witch Head Nebula", "NGC 2440 - Meathook Nebula", "Messier 16 - Eagle Nebula", "NGC 2392 - Eskimo Nebula", "NGC 6888 - Crescent Nebula", "NGC 1514 - Crystal Ball Nebula", "NGC 6543 - Cat's Eye Nebula", "NGC 1360 - Rob's Batcave Nebula", "NGC 6334 - Cat's Paw Nebula", "NGC 3372 - Eta Carinae Nebula", "NGC 2237 - Rosette Nebula", "NGC 2818 - Planetary Nebula", "NGC 6300 - Butterfly Nebula", "NGC 7009 - Saturn Nebula", "NGC 6565 - Cat's Paw Nebula", "NGC 6164 - Jellyfish Nebula", "NGC 2447 - Running Chicken Nebula", "NGC 3324 - Gabriela Mistral Nebula", "NGC 2395 - Eskimo Nebula", "NGC 2362 - Tau Canis Majoris Cluster", "NGC 6337 - War and Peace Nebula", "NGC 2070 - Tarantula Nebula", "NGC 7635 - Bubble Nebula", "NGC 6357 - War and Peace Nebula", "NGC 346 - Small Magellanic Cloud Nebula")
)

underwater = (
    "Underwater",
    ("Clownfish", "Regal Tang Fish", "Blue Tang Fish", "Moorish Idol Fish", "Angelfish", "Lionfish", "Parrotfish", "Seahorse", "Boxfish", "Goby Fish", "Triggerfish", "Pufferfish", "Wrasse Fish", "Damsel Fish", "Anemonefish", "Chromis Fish", "Cardinalfish", "Butterflyfish", "Grouper Fish", "Tuna Fish", "Mahi-Mahi Fish", "Barracuda Fish", "Snapper Fish", "Moray Eel", "Cuttlefish", "Squid", "Octopus", "Nautilus", "Jellyfish", "Sea Anemone", "Coral Polyps", "Brain Coral", "Staghorn Coral", "Fire Coral", "Gorgonian Coral", "Sea Fan", "Bubble Coral", "Clam", "Oyster", "Mussel", "Sea Urchin", "Sea Cucumber", "Starfish", "Brittle Star", "Sand Dollar", "Sea Slug", "Nudibranch", "Sea Horse", "Sea Dragon", "Flatworm", "Ghost Pipefish", "Mantis Shrimp", "Boxer Crab", "Hermit Crab", "Spider Crab", "Decorator Crab", "Lobster", "Shrimp", "Krill", "Barnacle", "Sea Worm", "Sea Sponge", "Sea Squirt", "Tunicate", "Comb Jelly", "Sea Walnut", "Salp", "Sea Walnut", "Comb Jelly", "Siphonophore", "Sea Butterfly", "Sea Angel", "Hagfish", "Lamprey", "Giant Tube Worm", "Hydrothermal Vent Crab", "Vampire Squid", "Gulper Eel", "Giant Isopod", "Frilled Shark", "Goblin Shark", "Cookiecutter Shark", "Megamouth Shark", "Anglerfish", "Barreleye Fish", "Hatchetfish", "Deep-Sea Hatchetfish", "Dragonfish", "Fangtooth Fish", "Viperfish", "Blobfish", "Dumbo Octopus", "Giant Squid", "Colossal Squid", "Mimic Octopus", "Blue-Ringed Octopus", "Leafy Seadragon", "Weedy Seadragon", "Pygmy Seahorse")
)

fantasy= (
    "Fantasy",
    ("Dragon Fantasy Art", "Unicorn Illustration", "Mermaid Digital Painting", "Phoenix Mythical Bird", "Fairy Tale Forest", "Magical Castle Art", "Elf Kingdom Illustration", "Wizard Tower Fantasy", "Centaur Artwork", "Goblin Creature Drawing", "Pixie Fantasy Art", "Enchanted Meadow Scene", "Dwarf Kingdom Illustration", "Griffin Mythical Beast", "Sorcerer Fantasy Art", "Magic Portal Concept", "Kraken Sea Monster", "Pegasus Flying Horse", "Celtic Mythology Art", "Nymph Fantasy Illustration", "Wizard Spell Casting", "Chimera Mythical Creature", "Troll Fantasy Art", "Satyr Forest Creature", "Hydra Mythical Serpent", "Fairy Ring Enchantment", "Minotaur Labyrinth Art", "Centaurs Galloping", "Magical Book of Spells", "Frost Giant Fantasy Art", "Leprechaun Illustration", "Siren Song Artwork", "Jinn Fantasy Genie", "Banshee Wailing Spirit", "Crystal Ball Divination", "Gryphon Mythical Creature", "Fey Folk Illustration", "Wizard Hat and Wand", "Manticore Mythical Beast", "Enchanted Garden Scene", "Treant Fantasy Tree", "Elven Archer Art", "Orc Warrior Drawing", "Kelpie Water Horse", "Fable World Illustration", "Golden Griffin Art", "Fairy Godmother Concept", "Vampire Castle Scene", "Hobbit Village Art", "Witch's Cauldron Brew", "Sorceress Fantasy Art", "Gargoyle Statue Drawing", "Rainbow Bridge Fantasy", "Night Elf Archer", "Dragon Rider Illustration", "Medusa Gorgon Art", "Fable Kingdom Scene", "Fire Elemental Creature", "Shadowy Goblin King", "Forest Guardian Spirit", "Unicorn Foal Art", "Dragon Egg Nest", "Arcane Rune Symbols", "Mystical Waterfall Scene", "Ancient Runes Enchantment", "Winged Serpent Art", "Magical Quill and Book", "Lunar Fairy Night", "Woodland Sprite Fantasy", "Cursed Castle Art", "Floating Island Concept", "Celestial Unicorn", "Majestic Griffin Drawing", "Enchanted River Scene", "Sorcery Spellbook Art", "Mystic Forest Clearing", "Wizard's Laboratory Illustration", "Nightmare Horse Creature", "Moonlit Enchanted Garden", "Mystical Beast Taming", "Sorceress Crystal Ball", "Fairy Queen Art", "Golden Phoenix Rising", "Starlit Sky Castle", "Mystic Moonlit Lake", "Enchanting Lantern Scene", "Dreamlike Fantasy World", "Vivid Fantasy Tapestry", "Elven Kingdom Sunset", "Crystalized Unicorn Horn", "Fantasy Creature Anatomy", "Whimsical Wonderland Art", "Magical Lantern Forest", "Dreamy Castle in the Sky", "Cauldron Brewing Potion", "Glowing Fairy Wings", "Wizard's Workshop Scene", "Floating City Concept", "Feywild Forest Art", "Ethereal Spirit Creatures", "Frosty Ice Dragon", "Celestial Being Art", "Guardian of the Portal", "Magical Guardian Owl", "Harpy Mythical Bird", "Cosmic Unicorn Illustration", "Sorceress Tower Art", "Astral Projection Fantasy", "Dreamcatcher Illustration", "Fey Dragon Fantasy", "Elemental Mage Artwork")
)

ancient = (
    "Ancient",
    ("Tyrannosaurus rex", "Velociraptor", "Triceratops", "Stegosaurus", "Brachiosaurus", "Pteranodon", "Mammoth", "Sabertooth Tiger", "Woolly Rhino", "Dodo Bird", "Quetzalcoatlus", "Archaeopteryx", "Ankylosaurus", "Spinosaurus", "Allosaurus", "Ichthyosaur", "Plesiosaur", "Megalodon", "Glyptodon", "Smilodon", "Mastodon", "Dimetrodon", "Woolly Mammoth", "Neanderthal", "Homo erectus", "Cro-Magnon", "Australopithecus", "Peking Man", "Denisovan", "Homo habilis", "Dinornis (Moas)", "Deinonychus", "Parasaurolophus", "Dilophosaurus", "Cave Bear", "Gigantopithecus", "Hesperornis", "Thylacine", "Irish Elk", "Coelophysis", "Compsognathus", "Dromaeosaurus", "Carnotaurus", "Troodon", "Oviraptor", "Iguanodon", "Brontosaurus", "Megaloceros", "Pterosaur", "Achelousaurus", "Achillobator", "Alamosaurus", "Alvarezsaurus", "Australovenator", "Barapasaurus", "Baryonyx", "Camarasaurus", "Camptosaurus", "Carnotaurus", "Ceratosaurus", "Chasmosaurus", "Corythosaurus", "Deinonychus", "Diplodocus", "Dryosaurus", "Edmontosaurus", "Elasmosaurus", "Euoplocephalus", "Giganotosaurus", "Herrerasaurus", "Iguanodon", "Indominus rex", "Indoraptor", "Kentrosaurus", "Majungasaurus", "Microceratus", "Nigersaurus", "Nothosaurus", "Ouranosaurus", "Oviraptor", "Pachycephalosaurus", "Parasaurolophus", "Protoceratops", "Pteranodon", "Pachyrhinosaurus", "Qianzhousaurus", "Quetzalcoatlus", "Rugops", "Stegosaurus", "Spinosaurus", "Struthiomimus", "Suchomimus", "Tarbosaurus", "Therizinosaurus", "Triceratops", "Troodon", "Tyrannosaurus rex", "Utahraptor", "Velociraptor", "Yi Dinosaur", "Zalmoxes", "Zephyrosaurus")
)

botanical = (
    "Botanical",
    ("Rose Flower", "Sunflower", "Orchid", "Tulip", "Cactus Plant", "Succulent Garden", "Bamboo Forest", "Bonsai Tree", "Cherry Blossom", "Lily Flower", "Poppy Plant", "Daisy", "Daffodil", "Hibiscus", "Maple Leaf", "Fern Plant", "Ivy Vine", "Lotus Flower", "Palm Tree", "Bougainvillea", "Carnation", "Dahlia", "Marigold", "Aloe Vera", "Cactus Illustration", "Botanical Sketch", "Watercolor Botanical", "Vintage Botanical", "Wildflower Meadow", "Rose Garden", "Floral Pattern", "Herb Garden", "Tropical Plants", "Monstera Leaf", "Fiddle Leaf Fig", "Sundew Plant", "Venus Flytrap", "Pitcher Plant", "Acanthophylla", "Cobra Plant", "Cyclamen Flower", "Dandelion", "Eucalyptus Leaves", "Fern Frond", "Ginger Plant", "Heliconia Flower", "Impatiens Plant", "Jasmine Flower", "Kale Plant", "Lavender", "Morning Glory", "Nasturtium", "Oregano Plant", "Poinsettia", "Queen Anne's Lace", "Rhododendron", "Sage Plant", "Thistle Flower", "Umbrella Plant", "Valerian Flower", "Weeping Willow", "Xerophyte Plants", "Yarrow Flower", "Zinnia Plant", "Bromeliad", "Calathea Leaf", "Drimiopsis", "Echeveria Succulent", "Fuchsia Plant", "Gloxinia Flower", "Hoya Plant", "Iris Flower", "Jade Plant", "Kalanchoe", "Lisianthus", "Mimosa Pudica", "Nepenthes", "Oxalis Plant", "Passiflora", "Quince Flower", "Rafflesia Flower", "Snake Plant", "Tiger Lily", "Umbrella Thorn Acacia", "Viola Plant", "Wisteria Vine", "Xanthorrhoea", "Yucca Plant", "Zamia Plant", "Acanthus Mollis", "Bird of Paradise Flower", "Clematis Vine", "Dianthus Flower", "Elephant Ear Plant", "Foxtail Lily", "Geranium Flower", "Hosta Plant", "Ixia Flower", "Jatropha Plant", "Kerria Japonica", "Lilac Flower", "Monarda Flower", "Nerium Oleander", "Oncidium Orchid", "Pentas Flower", "Quassia Amara", "Ranunculus Flower", "Senecio Plant", "Tradescantia Zebrina", "Uvularia Grandiflora", "Viburnum Plant", "Wollemi Pine", "Xanthosoma Plant", "Yew Plant", "Zantedeschia Plant")
)
