# Generated by Django 4.2.5 on 2024-01-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nftmysterybox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.CharField(default=' ', max_length=300)),
                ('transactions_with_same_block_time', models.CharField(default=' ', max_length=300)),
                ('block_time', models.IntegerField(default=0)),
                ('lock', models.CharField(default='Open', max_length=5)),
                ('lock_time', models.IntegerField(default=0)),
            ],
        ),
    ]
